### PR TITLE
Merge dev to master

### PR DESCRIPTION
**Pull request by jeffvg**
Fixes # .

#### Changes proposed in this Pull Request:
- update master with R22 work
- 
- 

#### To Test:
-

### CODE REVIEW

**Review by emclaug2 — APPROVED** [review]

**Comment by emclaug2** [comment]
Testing this now in stackblitz:
https://stackblitz.com/github/brightlayer-ui/angular-design-patterns/tree/dev

AppBar Dropdown Toolbar example doesn't work.

**Comment by jeffvg** [comment]
> Testing this now in stackblitz: https://stackblitz.com/github/brightlayer-ui/angular-design-patterns/tree/dev
> 
> AppBar Dropdown Toolbar example doesn't work.

it seems to work only if you open project in new window

image

**Comment by huayunh** [comment]
Issue logged #179

**Comment by jeffvg** [comment]
https://github.com/brightlayer-ui/angular-design-patterns/pull/180

**Review by emclaug2 — APPROVED** [review]

**Comment by jeffvg** [comment]
found one more issue in stackblitz. logging issue now
image

**Comment by jeffvg** [comment]
@emclaug2  I verified everything in stackblitz and issues are fixed

**Review by daileytj — APPROVED** [review]
Found some issues with colors in the tree structure example. Bugs wrote up. Otherwise looks good
https://github.com/brightlayer-ui/angular-design-patterns/issues/183
https://github.com/brightlayer-ui/angular-design-patterns/issues/184

**Comment by jeffvg** [comment]
just noticed the root read me needs updated with latest examples
https://github.com/brightlayer-ui/angular-design-patterns#current-patterns

**Comment by jeffvg** [comment]
> 

doing this now

**Review by andrupu — APPROVED** [review]
README.md example lists look to be matching between Angular and React.

**Review by huayunh — APPROVED** [review]

**Pull request merged**
