### PR TITLE
Feature/2552 multiselect

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
-  Multi Select List 

image

#### To Test:
- http://localhost:4200/lists/multi-select-list

### CODE REVIEW

**Comment by huayunh** [comment]
@mvbela

**Comment by ektasawant** [comment]
1. When we delete all items from `Today` then Select All checkbox of yesterday gets invisible.
Screenshot 2021-12-24 at 3 15 02 PM

2. Selected row background is not as per figma.
Screenshot 2021-12-27 at 1 23 41 PM

3. Mobile view showing selected checkbox when all items are deleted.
Screenshot 2021-12-27 at 1 25 55 PM

**Comment by daileytj** [comment]
Updated this for @emclaug2 😃 ... @ektasawant, Can you take a second look at this?

**Comment by ektasawant** [comment]
> Updated this for @emclaug2 😃 ... @ektasawant, Can you take a second look at this?

Working perfectly 👍 .

**Review by ektasawant — APPROVED** [review]

**Pull request merged**
