### PR TITLE
Fixed expansion panel indicator transform

### LINKED ISSUE #158: Center-Align Chevrons
#### Describe the bug
Chevrons should be center aligned in the Tree Structure example.
This might be a bigger issue; should this apply to all chevrons
Should this be a themes change?  Might need to understand why these icons aren't centered in the first place.

#### What is the expected behavior?
Chevron should be center-aligned when opened or closed. 

#### What are the steps to reproduce?
Go to tree structure demo.
Look at the chevrons.

#### Screenshots or links to minimum reproduction example
140258600-de3623fa-bdda-4049-8356-391f2d4879d0

#### Environment

Window Chrome
		
#### Anything else to add?
Nope

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes #158 

#### Changes proposed in this Pull Request:
- Updated the position of chevron

#### Screenshots:
**Desktop**
Screenshot 2022-01-05 at 2 25 44 PM

**Mobile**

#### To Test:
- yarn start
- Open Tree Structure under Lists
- Open any of the folder in the tree structure list

### CODE REVIEW

**Comment by huayunh** [comment]
I haven’t look into this deeply yet, but  for the sake of addressing the question raised in the bug report —Does this deserve a theme change?

**Review by emclaug2 — COMMENTED** [review]
Let's move this fix over to the angular themes, here: https://github.com/brightlayer-ui/angular-themes/blob/dev/_common.scss
This file is for common one-off non-color adjustments. 

But @bkarambe you've inverted the expand/collapse icon. They're now centered and look good, but they are inverted. Just apply a margin to the original icon instead. 

From Angular material docs: 

Closed: 
image

Open:
image

**Comment by ektasawant** [comment]
> https://github.com/brightlayer-ui/angular-themes/blob/dev/_common.scss



> Let's move this fix over to the angular themes, here: https://github.com/brightlayer-ui/angular-themes/blob/dev/_common.scss This file is for common one-off non-color adjustments.
> 
> But @bkarambe you've inverted the expand/collapse icon. They're now centered and look good, but they are inverted. Just apply a margin to the original icon instead.
> 
> From Angular material docs:
> 
> Closed: image
> 
> Open: image

Agree with Evan, instead of rotate prop can we use this code https://github.com/brightlayer-ui/angular-design-patterns/blob/dev/src/app/pages/list/status-list/status-list.component.scss#L44 ?

**Comment by huayunh** [comment]
Woo even the Ng Material expansion panel chevron looks off centered to me from Evan’s screenshot. Can we also log a bug in Angular Material’s repo, and leave the bug link here?

**Comment by bkarambe** [comment]
Closing this PR, as it will be taken care in https://github.com/brightlayer-ui/angular-themes/pull/51

**Pull request closed without merging**
